create table fa_auth_rule
(
    id          int unsigned auto_increment
        primary key,
    type        enum ('menu', 'file') default 'file'        not null comment 'menu为菜单,file为权限节点',
    pid         int unsigned          default '0'           not null comment '父ID',
    name        varchar(100)          default ''            null comment '规则名称',
    title       varchar(50)           default ''            null comment '规则名称',
    icon        varchar(50)           default ''            null comment '图标',
    url         varchar(255)          default ''            null comment '规则URL',
    `condition` varchar(255)          default ''            null comment '条件',
    remark      varchar(255)          default ''            null comment '备注',
    ismenu      tinyint unsigned      default '0'           not null comment '是否为菜单',
    menutype    enum ('addtabs', 'blank', 'dialog', 'ajax') null comment '菜单类型',
    extend      varchar(255)          default ''            null comment '扩展属性',
    py          varchar(30)           default ''            null comment '拼音首字母',
    pinyin      varchar(100)          default ''            null comment '拼音',
    createtime  int                                         null comment '创建时间',
    updatetime  int                                         null comment '更新时间',
    weigh       int                   default 0             not null comment '权重',
    status      varchar(30)           default ''            null comment '状态',
    constraint name
        unique (name)
)
    comment '节点表' collate = utf8mb4_unicode_ci;

create index pid
    on fa_auth_rule (pid);

create index weigh
    on fa_auth_rule (weigh);

INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (1, 'file', 0, 'dashboard', 'Dashboard', 'fa fa-dashboard', '', '', 'Dashboard tips', 1, null, '', 'kzt', 'kongzhitai', 1491635035, 1657114511, 143, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (2, 'file', 0, 'general', 'General', 'fa fa-cogs', '', '', '', 1, null, '', 'cggl', 'changguiguanli', 1491635035, 1491635035, 137, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (3, 'file', 0, 'category', 'Category', 'fa fa-leaf', '', '', 'Category tips', 1, null, '', 'flgl', 'fenleiguanli', 1491635035, 1650716965, 119, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (4, 'file', 0, 'addon', 'Addon', 'fa fa-rocket', '', '', 'Addon tips', 0, null, '', 'cjgl', 'chajianguanli', 1491635035, 1654885705, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (5, 'file', 0, 'auth', 'Auth', 'fa fa-group', '', '', '', 1, null, '', 'qxgl', 'quanxianguanli', 1491635035, 1491635035, 99, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (6, 'file', 2, 'general/config', 'Config', 'fa fa-cog', '', '', 'Config tips', 1, null, '', 'xtpz', 'xitongpeizhi', 1491635035, 1642565888, 60, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (7, 'file', 2, 'general/attachment', 'Attachment', 'fa fa-file-image-o', '', '', 'Attachment tips', 1, null, '', 'fjgl', 'fujianguanli', 1491635035, 1650716871, 53, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (8, 'file', 2, 'general/profile', 'Profile', 'fa fa-user', '', '', '', 1, null, '', 'grzl', 'gerenziliao', 1491635035, 1650716864, 34, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (9, 'file', 5, 'auth/admin', 'Admin', 'fa fa-user', '', '', 'Admin tips', 1, null, '', 'glygl', 'guanliyuanguanli', 1491635035, 1491635035, 118, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (10, 'file', 5, 'auth/adminlog', 'Admin log', 'fa fa-list-alt', '', '', 'Admin log tips', 1, null, '', 'glyrz', 'guanliyuanrizhi', 1491635035, 1650716991, 113, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (11, 'file', 5, 'auth/group', 'Group', 'fa fa-group', '', '', 'Group tips', 1, null, '', 'jsz', 'juesezu', 1491635035, 1491635035, 109, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (12, 'file', 5, 'auth/rule', 'Rule', 'fa fa-bars', '', '', 'Rule tips', 1, null, '', 'cdgz', 'caidanguize', 1491635035, 1491635035, 104, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (13, 'file', 1, 'dashboard/index', 'View', 'fa fa-circle-o', '', '', '', 1, null, '', 'zk', 'zhakan', 1491635035, 1650717361, 136, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (14, 'file', 1, 'dashboard/add', 'Add', 'fa fa-circle-o', '', '', '', 0, null, '', 'tj', 'tianjia', 1491635035, 1650967394, 135, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (15, 'file', 1, 'dashboard/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, null, '', 'sc', 'shanchu', 1491635035, 1657119964, 133, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (16, 'file', 1, 'dashboard/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, null, '', 'bj', 'bianji', 1491635035, 1657119965, 134, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (17, 'file', 1, 'dashboard/multi', 'Multi', 'fa fa-circle-o', '', '', '', 0, null, '', 'plgx', 'pilianggengxin', 1491635035, 1657122621, 132, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (18, 'file', 6, 'general/config/index', 'View', 'fa fa-circle-o', '', '', '', 1, null, '', 'zk', 'zhakan', 1491635035, 1650717400, 52, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (19, 'file', 6, 'general/config/add', 'Add', 'fa fa-circle-o', '', '', '', 0, null, '', 'tj', 'tianjia', 1491635035, 1650967432, 51, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (20, 'file', 6, 'general/config/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, null, '', 'bj', 'bianji', 1491635035, 1650967448, 50, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (21, 'file', 6, 'general/config/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 49, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (22, 'file', 6, 'general/config/multi', 'Multi', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 48, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (23, 'file', 7, 'general/attachment/index', 'View', 'fa fa-circle-o', '', '', 'Attachment tips', 0, null, '', '', '', 1491635035, 1491635035, 59, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (24, 'file', 7, 'general/attachment/select', 'Select attachment', 'fa fa-circle-o', '', '', '', 1, null, '', 'xzfj', 'xuanzefujian', 1491635035, 1650717451, 58, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (25, 'file', 7, 'general/attachment/add', 'Add', 'fa fa-circle-o', '', '', '', 1, null, '', 'tj', 'tianjia', 1491635035, 1650899602, 57, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (26, 'file', 7, 'general/attachment/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 56, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (27, 'file', 7, 'general/attachment/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 55, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (28, 'file', 7, 'general/attachment/multi', 'Multi', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 54, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (29, 'file', 8, 'general/profile/index', 'View', 'fa fa-circle-o', '', '', '', 1, null, '', 'zk', 'zhakan', 1491635035, 1650724482, 33, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (30, 'file', 8, 'general/profile/update', 'Update profile', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 32, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (31, 'file', 8, 'general/profile/add', '添加', 'fa fa-circle-o', '', '', '', 0, 'addtabs', '', 'tj', 'tianjia', 1491635035, 1651132249, 31, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (32, 'file', 8, 'general/profile/edit', '编辑', 'fa fa-circle-o', '', '', '', 0, 'addtabs', '', 'bj', 'bianji', 1491635035, 1651132259, 30, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (33, 'file', 8, 'general/profile/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 29, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (34, 'file', 8, 'general/profile/multi', 'Multi', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 28, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (35, 'file', 3, 'category/index', 'View', 'fa fa-circle-o', '', '', 'Category tips', 0, null, '', '', '', 1491635035, 1491635035, 142, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (36, 'file', 3, 'category/add', 'Add', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 141, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (37, 'file', 3, 'category/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 140, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (38, 'file', 3, 'category/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 139, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (39, 'file', 3, 'category/multi', 'Multi', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 138, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (40, 'file', 9, 'auth/admin/index', 'View', 'fa fa-circle-o', '', '', 'Admin tips', 0, null, '', '', '', 1491635035, 1491635035, 117, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (41, 'file', 9, 'auth/admin/add', 'Add', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 116, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (42, 'file', 9, 'auth/admin/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 115, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (43, 'file', 9, 'auth/admin/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 114, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (44, 'file', 10, 'auth/adminlog/index', 'View', 'fa fa-circle-o', '', '', 'Admin log tips', 1, null, '', 'zk', 'zhakan', 1491635035, 1650899622, 112, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (45, 'file', 10, 'auth/adminlog/detail', 'Detail', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 111, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (46, 'file', 10, 'auth/adminlog/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 110, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (47, 'file', 11, 'auth/group/index', 'View', 'fa fa-circle-o', '', '', 'Group tips', 0, null, '', '', '', 1491635035, 1491635035, 108, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (48, 'file', 11, 'auth/group/add', 'Add', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 107, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (49, 'file', 11, 'auth/group/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 106, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (50, 'file', 11, 'auth/group/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 105, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (51, 'file', 12, 'auth/rule/index', 'View', 'fa fa-circle-o', '', '', 'Rule tips', 0, null, '', '', '', 1491635035, 1491635035, 103, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (52, 'file', 12, 'auth/rule/add', 'Add', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 102, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (53, 'file', 12, 'auth/rule/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 101, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (54, 'file', 12, 'auth/rule/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 100, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (55, 'file', 4, 'addon/index', 'View', 'fa fa-circle-o', '', '', 'Addon tips', 0, null, '', '', '', 1491635035, 1491635035, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (56, 'file', 4, 'addon/add', 'Add', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (57, 'file', 4, 'addon/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (58, 'file', 4, 'addon/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (59, 'file', 4, 'addon/downloaded', 'Local addon', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (60, 'file', 4, 'addon/state', 'Update state', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (63, 'file', 4, 'addon/config', 'Setting', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (64, 'file', 4, 'addon/refresh', 'Refresh', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (65, 'file', 4, 'addon/multi', 'Multi', 'fa fa-circle-o', '', '', '', 0, null, '', '', '', 1491635035, 1491635035, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (85, 'file', 0, 'command', '在线命令管理', 'fa fa-terminal', '', '', '', 1, null, '', 'zxmlgl', 'zaixianminglingguanli', 1629175556, 1657435799, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (86, 'file', 85, 'command/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1629175556, 1629175556, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (87, 'file', 85, 'command/add', '添加', 'fa fa-circle-o', '', '', '', 0, null, '', 'tj', 'tianjia', 1629175556, 1629175556, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (88, 'file', 85, 'command/detail', '详情', 'fa fa-circle-o', '', '', '', 0, null, '', 'xq', 'xiangqing', 1629175556, 1629175556, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (89, 'file', 85, 'command/execute', '运行', 'fa fa-circle-o', '', '', '', 0, null, '', 'yx', 'yunxing', 1629175556, 1629175556, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (90, 'file', 85, 'command/del', '删除', 'fa fa-circle-o', '', '', '', 0, null, '', 'sc', 'shanchu', 1629175556, 1629175556, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (91, 'file', 85, 'command/multi', '批量更新', 'fa fa-circle-o', '', '', '', 0, null, '', 'plgx', 'pilianggengxin', 1629175556, 1629175556, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (92, 'file', 2, 'banner/index', '轮播图管理', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'lbtgl', 'lunbotuguanli', 1629185286, 1629185286, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (93, 'file', 2, 'notice/index', '内容精选管理', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'nrjxgl', 'neirongjingxuanguanli', 1629185305, 1649231558, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (94, 'file', 2, 'news/index', '新闻资讯管理', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'xwzxgl', 'xinwenzixunguanli', 1629185323, 1650724339, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (95, 'file', 0, 'user', '会员管理', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'hygl', 'huiyuanguanli', 1629185342, 1635227937, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (96, 'file', 0, 'bill', '财务管理', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'cwgl', 'caiwuguanli', 1629185351, 1629185351, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (97, 'file', 0, 'award', '奖项管理', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'jxgl', 'jiangxiangguanli', 1629185361, 1649231014, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (98, 'file', 95, 'users', '会员列表', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'hylb', 'huiyuanliebiao', 1629185524, 1635227953, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (99, 'file', 95, 'rank/index', '会员级别', 'fa fa-circle-o', '', '', '', 0, 'addtabs', '', 'hyjb', 'huiyuanjibie', 1629185535, 1637920888, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (100, 'file', 95, 'role/index', '会员角色', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'hyjs', 'huiyuanjuese', 1629185553, 1637920590, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (101, 'file', 95, 'users/team', '团队图谱', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'tdtp', 'tuanduitupu', 1629185935, 1636610226, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (102, 'file', 96, 'currency/index', '币种管理', 'fa fa-circle-o', '', '', '', 0, 'addtabs', '', 'bzgl', 'bizhongguanli', 1629189724, 1637920802, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (103, 'file', 96, 'bill/index', '账单流水', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'zdls', 'zhangdanliushui', 1629189739, 1629189739, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (104, 'file', 96, 'funds/index', '后台充值/扣费记录', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'htczkfjl', 'houtaichongzhikoufeijilu', 1629191387, 1629191387, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (105, 'file', 97, 'award/index', '奖项列表', 'fa fa-circle-o', '', '', '推荐奖励只有受邀用户正确实名之后才会记录
注册空投在受邀用户注册之后就会进行判断', 1, 'addtabs', '', 'jxlb', 'jiangxiangliebiao', 1629192218, 1666849172, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (106, 'file', 97, 'award_record/index', '发奖记录', 'fa fa-circle-o', '', '', '推荐奖励只有受邀用户正确实名之后才会记录
注册空投在受邀用户注册之后就会进行判断', 1, 'addtabs', '', 'fjjl', 'fajiangjilu', 1629192255, 1666849213, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (107, 'file', 148, 'config_draw/index', '提现配置', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'txpz', 'tixianpeizhi', 1629200727, 1636531996, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (108, 'file', 148, 'draw_record/index', '提现记录', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'txjl', 'tixianjilu', 1629201550, 1636532002, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (114, 'file', 98, 'users/edit', '会员编辑', 'fa fa-circle-o', '', '', '', 0, 'addtabs', '', 'hybj', 'huiyuanbianji', 1634724576, 1634724576, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (115, 'file', 98, 'users/add', '会员添加', 'fa fa-circle-o', '', '', '', 0, 'addtabs', '', 'hytj', 'huiyuantianjia', 1634724594, 1634724594, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (116, 'file', 98, 'users/del', '会员删除', 'fa fa-circle-o', '', '', '', 0, 'addtabs', '', 'hysc', 'huiyuanshanchu', 1634724608, 1634724608, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (117, 'file', 98, 'users/export', '会员导出', 'fa fa-circle-o', '', '', '', 0, 'addtabs', '', 'hydc', 'huiyuandaochu', 1634724669, 1634724669, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (118, 'file', 108, 'draw_record/pass', '提现通过', 'fa fa-circle-o', '', '', '', 0, 'addtabs', '', 'txtg', 'tixiantongguo', 1634783940, 1651037955, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (119, 'file', 108, 'draw_record/refuse', '提现拒绝', 'fa fa-circle-o', '', '', '', 0, 'addtabs', '', 'txjj', 'tixianjujue', 1634783956, 1651037962, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (135, 'file', 98, 'users/index', '查看', 'fa fa-circle-o', '', '', '', 0, 'addtabs', '', 'zk', 'zhakan', 1635227962, 1635227962, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (136, 'file', 137, 'goods/index', '藏品管理', 'fa fa-circle-o', '', '', '商品上链之前确保系统账户已经上链，否则会提示用户不存在或已禁用', 1, 'addtabs', '', 'cpgl', 'cangpinguanli', 1635237820, 1666884608, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (137, 'file', 0, 'goods', '藏品管理', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'ppgl', 'paipinguanli', 1636525513, 1637205597, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (148, 'file', 0, 'draw', '提现管理', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'txgl', 'tixianguanli', 1636531989, 1636531989, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (150, 'file', 2, 'feedback/index', '问题反馈', 'fa fa-circle-o', '', '', '', 0, 'addtabs', '', 'wtfk', 'wentifankui', 1636533528, 1637920452, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (155, 'file', 137, 'orders/index', '藏品订单管理', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'spddgl', 'shangpindingdanguanli', 1636613104, 1636613104, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (164, 'file', 137, 'goods_users/index', '会员藏品管理', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'hyppgl', 'huiyuanpaipinguanli', 1637205567, 1637205567, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (168, 'file', 137, 'goods_transfer/index', '藏品转增记录', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'cpzzjl', 'cangpinzhuanzengjilu', 1638932102, 1638932102, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (169, 'file', 137, 'goods_category/index', '藏品分类管理', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'cpflgl', 'cangpinfenleiguanli', 1639016458, 1639016458, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (170, 'file', 137, 'calendar/index', '发售日历', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'fsrl', 'fashourili', 1649298182, 1649298182, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (171, 'file', 178, 'manghe_award_record', '盲盒中奖纪录', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'mhzjjl', 'manghezhongjiangjilu', 1650785043, 1650785130, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (172, 'file', 171, 'manghe_award_record/import', 'Import', 'fa fa-circle-o', '', '', '', 0, null, '', 'dr', 'daoru', 1650785043, 1650785043, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (173, 'file', 171, 'manghe_award_record/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1650785043, 1650785043, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (174, 'file', 171, 'manghe_award_record/add', '添加', 'fa fa-circle-o', '', '', '', 0, null, '', 'tj', 'tianjia', 1650785043, 1650785043, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (175, 'file', 171, 'manghe_award_record/edit', '编辑', 'fa fa-circle-o', '', '', '', 0, null, '', 'bj', 'bianji', 1650785043, 1650785043, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (176, 'file', 171, 'manghe_award_record/del', '删除', 'fa fa-circle-o', '', '', '', 0, null, '', 'sc', 'shanchu', 1650785043, 1650785043, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (177, 'file', 171, 'manghe_award_record/multi', '批量更新', 'fa fa-circle-o', '', '', '', 0, null, '', 'plgx', 'pilianggengxin', 1650785043, 1650785043, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (178, 'file', 0, 'manghe', '盲盒管理', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'mhgl', 'mangheguanli', 1650785108, 1650785108, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (179, 'file', 178, 'goods_manghe_users', '用户盲盒管理', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'yhmhgl', 'yonghumangheguanli', 1650799419, 1650799437, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (180, 'file', 179, 'goods_manghe_users/import', 'Import', 'fa fa-circle-o', '', '', '', 0, null, '', 'dr', 'daoru', 1650799420, 1650799420, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (181, 'file', 179, 'goods_manghe_users/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1650799420, 1650799420, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (182, 'file', 179, 'goods_manghe_users/add', '添加', 'fa fa-circle-o', '', '', '', 0, null, '', 'tj', 'tianjia', 1650799420, 1650799420, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (183, 'file', 179, 'goods_manghe_users/edit', '编辑', 'fa fa-circle-o', '', '', '', 0, null, '', 'bj', 'bianji', 1650799420, 1650799420, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (184, 'file', 179, 'goods_manghe_users/del', '删除', 'fa fa-circle-o', '', '', '', 0, null, '', 'sc', 'shanchu', 1650799420, 1650799420, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (185, 'file', 179, 'goods_manghe_users/multi', '批量更新', 'fa fa-circle-o', '', '', '', 0, null, '', 'plgx', 'pilianggengxin', 1650799420, 1650799420, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (186, 'file', 178, 'manghe_banner', '盲盒轮播管理', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'mhlbgl', 'manghelunboguanli', 1650864621, 1650864640, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (187, 'file', 186, 'manghe_banner/import', 'Import', 'fa fa-circle-o', '', '', '', 0, null, '', 'dr', 'daoru', 1650864621, 1650864621, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (188, 'file', 186, 'manghe_banner/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1650864621, 1650864621, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (189, 'file', 186, 'manghe_banner/add', '添加', 'fa fa-circle-o', '', '', '', 0, null, '', 'tj', 'tianjia', 1650864621, 1650864621, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (190, 'file', 186, 'manghe_banner/edit', '编辑', 'fa fa-circle-o', '', '', '', 0, null, '', 'bj', 'bianji', 1650864621, 1650864621, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (191, 'file', 186, 'manghe_banner/del', '删除', 'fa fa-circle-o', '', '', '', 0, null, '', 'sc', 'shanchu', 1650864621, 1650864621, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (192, 'file', 186, 'manghe_banner/multi', '批量更新', 'fa fa-circle-o', '', '', '', 0, null, '', 'plgx', 'pilianggengxin', 1650864621, 1650864621, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (193, 'file', 200, 'chip_users', '用户碎片管理', 'fa fa-circle-o', '', '', '', 0, 'addtabs', '', 'yhspgl', 'yonghusuipianguanli', 1650869627, 1657086615, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (194, 'file', 193, 'chip_users/import', 'Import', 'fa fa-circle-o', '', '', '', 0, null, '', 'dr', 'daoru', 1650869627, 1650869627, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (195, 'file', 193, 'chip_users/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1650869627, 1650869627, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (196, 'file', 193, 'chip_users/add', '添加', 'fa fa-circle-o', '', '', '', 0, null, '', 'tj', 'tianjia', 1650869627, 1650869627, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (197, 'file', 193, 'chip_users/edit', '编辑', 'fa fa-circle-o', '', '', '', 0, null, '', 'bj', 'bianji', 1650869627, 1650869627, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (198, 'file', 193, 'chip_users/del', '删除', 'fa fa-circle-o', '', '', '', 0, null, '', 'sc', 'shanchu', 1650869627, 1650869627, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (199, 'file', 193, 'chip_users/multi', '批量更新', 'fa fa-circle-o', '', '', '', 0, null, '', 'plgx', 'pilianggengxin', 1650869627, 1650869627, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (200, 'file', 0, 'hecheng', '合成管理', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'hcgl', 'hechengguanli', 1650869674, 1655135295, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (201, 'file', 200, 'chip_compose_record', '合成记录', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'hcjl', 'hechengjilu', 1650878416, 1655525043, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (202, 'file', 201, 'chip_compose_record/import', 'Import', 'fa fa-circle-o', '', '', '', 0, null, '', 'dr', 'daoru', 1650878416, 1650878416, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (203, 'file', 201, 'chip_compose_record/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1650878416, 1650878416, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (204, 'file', 201, 'chip_compose_record/add', '添加', 'fa fa-circle-o', '', '', '', 0, null, '', 'tj', 'tianjia', 1650878416, 1650878416, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (205, 'file', 201, 'chip_compose_record/edit', '编辑', 'fa fa-circle-o', '', '', '', 0, null, '', 'bj', 'bianji', 1650878416, 1650878416, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (206, 'file', 201, 'chip_compose_record/del', '删除', 'fa fa-circle-o', '', '', '', 0, null, '', 'sc', 'shanchu', 1650878416, 1650878416, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (207, 'file', 201, 'chip_compose_record/multi', '批量更新', 'fa fa-circle-o', '', '', '', 0, null, '', 'plgx', 'pilianggengxin', 1650878416, 1650878416, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (208, 'file', 0, 'example', '开发示例管理', 'fa fa-magic', '', '', '', 0, null, '', 'kfslgl', 'kaifashiliguanli', 1651511589, 1656491859, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (209, 'file', 208, 'example/bootstraptable', '表格完整示例', 'fa fa-table', '', '', '', 1, null, '', 'bgwzsl', 'biaogewanzhengshili', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (210, 'file', 209, 'example/bootstraptable/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (211, 'file', 209, 'example/bootstraptable/detail', '详情', 'fa fa-circle-o', '', '', '', 0, null, '', 'xq', 'xiangqing', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (212, 'file', 209, 'example/bootstraptable/change', '变更', 'fa fa-circle-o', '', '', '', 0, null, '', 'bg', 'biangeng', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (213, 'file', 209, 'example/bootstraptable/del', '删除', 'fa fa-circle-o', '', '', '', 0, null, '', 'sc', 'shanchu', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (214, 'file', 209, 'example/bootstraptable/multi', '批量更新', 'fa fa-circle-o', '', '', '', 0, null, '', 'plgx', 'pilianggengxin', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (215, 'file', 208, 'example/customsearch', '自定义搜索', 'fa fa-table', '', '', '', 1, null, '', 'zdyss', 'zidingyisousuo', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (216, 'file', 215, 'example/customsearch/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (217, 'file', 215, 'example/customsearch/del', '删除', 'fa fa-circle-o', '', '', '', 0, null, '', 'sc', 'shanchu', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (218, 'file', 215, 'example/customsearch/multi', '批量更新', 'fa fa-circle-o', '', '', '', 0, null, '', 'plgx', 'pilianggengxin', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (219, 'file', 208, 'example/customform', '自定义表单示例', 'fa fa-edit', '', '', '', 1, null, '', 'zdybdsl', 'zidingyibiaodanshili', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (220, 'file', 219, 'example/customform/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (221, 'file', 208, 'example/tablelink', '表格联动示例', 'fa fa-table', '', '', '点击左侧日志列表，右侧的表格数据会显示指定管理员的日志列表', 1, null, '', 'bgldsl', 'biaogeliandongshili', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (222, 'file', 221, 'example/tablelink/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (223, 'file', 208, 'example/colorbadge', '彩色角标', 'fa fa-table', '', '', '左侧彩色的角标会根据当前数据量的大小进行更新', 1, null, '', 'csjb', 'caisejiaobiao', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (224, 'file', 223, 'example/colorbadge/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (225, 'file', 223, 'example/colorbadge/del', '删除', 'fa fa-circle-o', '', '', '', 0, null, '', 'sc', 'shanchu', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (226, 'file', 223, 'example/colorbadge/multi', '批量更新', 'fa fa-circle-o', '', '', '', 0, null, '', 'plgx', 'pilianggengxin', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (227, 'file', 208, 'example/controllerjump', '控制器间跳转', 'fa fa-table', '', '', '点击IP地址可以跳转到新的选项卡中查看指定IP的数据', 1, null, '', 'kzqjtz', 'kongzhiqijiantiaozhuan', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (228, 'file', 227, 'example/controllerjump/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (229, 'file', 227, 'example/controllerjump/del', '删除', 'fa fa-circle-o', '', '', '', 0, null, '', 'sc', 'shanchu', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (230, 'file', 227, 'example/controllerjump/multi', '批量更新', 'fa fa-circle-o', '', '', '', 0, null, '', 'plgx', 'pilianggengxin', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (231, 'file', 208, 'example/cxselect', '多级联动', 'fa fa-table', '', '', '基于jquery.cxselect实现的多级联动', 1, null, '', 'djld', 'duojiliandong', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (232, 'file', 231, 'example/cxselect/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (233, 'file', 231, 'example/cxselect/del', '删除', 'fa fa-circle-o', '', '', '', 0, null, '', 'sc', 'shanchu', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (234, 'file', 231, 'example/cxselect/multi', '批量更新', 'fa fa-circle-o', '', '', '', 0, null, '', 'plgx', 'pilianggengxin', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (235, 'file', 208, 'example/multitable', '多表格示例', 'fa fa-table', '', '', '展示在一个页面显示多个Bootstrap-table表格', 1, null, '', 'dbgsl', 'duobiaogeshili', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (236, 'file', 235, 'example/multitable/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (237, 'file', 235, 'example/multitable/del', '删除', 'fa fa-circle-o', '', '', '', 0, null, '', 'sc', 'shanchu', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (238, 'file', 235, 'example/multitable/multi', '批量更新', 'fa fa-circle-o', '', '', '', 0, null, '', 'plgx', 'pilianggengxin', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (239, 'file', 208, 'example/relationmodel', '关联模型示例', 'fa fa-table', '', '', '列表中的头像、用户名和昵称字段均从关联表中取出', 1, null, '', 'glmxsl', 'guanlianmoxingshili', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (240, 'file', 239, 'example/relationmodel/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (241, 'file', 239, 'example/relationmodel/del', '删除', 'fa fa-circle-o', '', '', '', 0, null, '', 'sc', 'shanchu', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (242, 'file', 239, 'example/relationmodel/multi', '批量更新', 'fa fa-circle-o', '', '', '', 0, null, '', 'plgx', 'pilianggengxin', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (243, 'file', 208, 'example/tabletemplate', '表格模板示例', 'fa fa-table', '', '', '', 1, null, '', 'bgmbsl', 'biaogemubanshili', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (244, 'file', 243, 'example/tabletemplate/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (245, 'file', 243, 'example/tabletemplate/detail', '详情', 'fa fa-circle-o', '', '', '', 0, null, '', 'xq', 'xiangqing', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (246, 'file', 243, 'example/tabletemplate/del', '删除', 'fa fa-circle-o', '', '', '', 0, null, '', 'sc', 'shanchu', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (247, 'file', 243, 'example/tabletemplate/multi', '批量更新', 'fa fa-circle-o', '', '', '', 0, null, '', 'plgx', 'pilianggengxin', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (248, 'file', 208, 'example/baidumap', '百度地图示例', 'fa fa-map-pin', '', '', '', 1, null, '', 'bddtsl', 'baiduditushili', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (249, 'file', 248, 'example/baidumap/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (250, 'file', 248, 'example/baidumap/map', '详情', 'fa fa-circle-o', '', '', '', 0, null, '', 'xq', 'xiangqing', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (251, 'file', 248, 'example/baidumap/del', '删除', 'fa fa-circle-o', '', '', '', 0, null, '', 'sc', 'shanchu', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (252, 'file', 208, 'example/echarts', '统计图表示例', 'fa fa-bar-chart', '', '', '', 1, null, '', 'tjtbsl', 'tongjitubiaoshili', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (253, 'file', 252, 'example/echarts/index', '查看', 'fa fa-circle-o', '', '', '', 0, null, '', 'zk', 'zhakan', 1651511589, 1651511589, 0, 'normal');
INSERT INTO bowen.fa_auth_rule (id, type, pid, name, title, icon, url, `condition`, remark, ismenu, menutype, extend, py, pinyin, createtime, updatetime, weigh, status) VALUES (256, 'file', 95, 'users_rank', '排行榜', 'fa fa-circle-o', '', '', '', 1, 'addtabs', '', 'phb', 'paihangbang', 1665311659, 1665311693, 0, 'normal');
